apiVersion: v1
kind: Pod
metadata:
  labels:
    ApplicationName: my_build
spec:
  containers:
  - name: my_image 
    image: base:0.1.0-1624030572
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    securityContext:
      runAsUser: 0
    tty: true
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock